-- Cleanup old objects

DROP TRIGGER SYS.TRG_LOG_USER_CREATION;

BEGIN
  FOR u IN (
    SELECT username FROM dba_users
    WHERE username IN ('MANAGERUSER','USER1','USER2')
  ) LOOP
    EXECUTE IMMEDIATE 'DROP USER '||u.username||' CASCADE';
  END LOOP;
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE
    'DROP TABLESPACE HOSPITAL_TBS INCLUDING CONTENTS AND DATAFILES';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
