-- Tablespace
CREATE TABLESPACE HOSPITAL_TBS
DATAFILE 'hospital_data.dbf' SIZE 100M
AUTOEXTEND ON NEXT 10M;

-- Manager
CREATE USER ManagerUser IDENTIFIED BY Manager123
DEFAULT TABLESPACE HOSPITAL_TBS
QUOTA UNLIMITED ON HOSPITAL_TBS;

GRANT CONNECT, RESOURCE, DBA, CREATE USER TO ManagerUser;

-- Users
CREATE USER User1 IDENTIFIED BY User123
DEFAULT TABLESPACE HOSPITAL_TBS
QUOTA UNLIMITED ON HOSPITAL_TBS;

CREATE USER User2 IDENTIFIED BY User123
DEFAULT TABLESPACE HOSPITAL_TBS
QUOTA UNLIMITED ON HOSPITAL_TBS;

GRANT CONNECT, RESOURCE, CREATE TABLE,
      CREATE SEQUENCE, CREATE TRIGGER,
      CREATE PROCEDURE TO User1;

GRANT CONNECT TO User2;
